#!/bin/sh

if [ "$#" -eq 3 ]; then
    java -jar /usr/share/java/saxon.jar -xsl:"$1" -s:"$2" -o:"$3"
elif [ "$#" -eq 2 ]; then
    java -jar /usr/share/java/saxon.jar -xsl:"$1" -s:"$2"
else
    echo "USAGE: $0 <xsl> <source> [<output>]"
    exit 1
fi

